version: '3.8'

services:

  frontend:
    image: daemondxx/balans-front:v0
    ports:
    - 80:80
    environment:
      - HOST_API=localhost


  backend:
    image: daemondxx/balans-back:v0
    volumes:
      - ./upload:/upload
    environment:
      - PORT_APP=3000
      - UPLOAD_PATH='./upload'
      - DB_HOST=mongo
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db_test/db:/data/db


